# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Green & Red World
tagline:          ''
description:      ''
url:              https://spring0070.github.io/gnr
baseurl:          /gnr

author:
  name:           'chungying_yu@hotmail.com'
  url:            ''

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
# Google Analytics
google_analytics: G-9P1MWQVWTF # 將 G-XXXXXXXXXX 替換為您的實際 GA4 追蹤 ID

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sass:
  load_paths:
    - _sass

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
disqus:
  shortname: GreenAndRed
  layout: default
  comments: true
